version: "3.7"
services:
  api:
    build:
      context: .
    image: desafio:api
    container_name: desafio-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: on-failure
    container_name: desafio-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DATABASE}
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@elo7.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
