info:
  created-by: rodrigo.vidal2006@gmail.com
  build-jdk: jdk1.11
  application-name: ${spring.application.name}
  implementation-build: ${build}
  implementation-version: ${version}

spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: 'health'
  endpoint:
    env:
      post:
        enabled: true
    info:
      enabled: true
    health:
      enabled: true
    scheduledtasks:
      enabled: true
    refresh:
      enabled: true
    shutdown:
      enabled: false
